name: chacha
description: An implementation of the symmetric ChaCha20 cipher and Poly1305 (MAC) as per RFC 8439.
version: 1.3.0
repository: https://github.com/carlosmakin/chacha

environment:
  sdk: ^3.8.0

dependencies:
  benchmark_harness: ^2.3.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
